name=VirtualGamePadArduino
version=1.0.0
author=Phil Schatzmann
maintainer=Phil Schatzmann 
sentence=ESP32 library for receiving VirtualGamePad data over WiFi (Colfer protocol)
paragraph=Enables ESP32 to act as a TCP server for receiving gamepad input from the VirtualGamePad ecosystem, with easy callback interface and full support for analog and digital controls.
category=Communication
url=https://github.com/pschatzmann/VirtualGamePadArduino
architectures=esp32
includes=GamepadServer.h
